recipebook/ledger/urls.py
from django.urls import path
from .views import recipe_list, recipe, recipe_maker, image_uploader

urlpatterns = [
    path('recipes/list/', recipe_list, name='recipe_list'),
    path('recipe/<int:key>/', recipe, name='recipe'),
    path('recipe/add/', recipe_maker, name='recipe_maker'),
    path('recipe/<int:key>/add_image/', image_uploader, name='image_uploader'),
]

app_name = 'ledger'

recipebook/recipebook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", include('ledger.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipebook/ledger/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    bio = models.TextField(max_length=255)

    def __str__(self):
        return self.name

class Ingredient(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('ingredient_detail', args=[str(self.name)])
    
class Recipe(models.Model):
    name = models.CharField(max_length=100)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, default=None)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('recipe_detail', args=[str(self.name)])
    
class RecipeIngredient(models.Model):
    quantity = models.CharField(max_length=10)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE, related_name='recipe')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='ingredients')
    
    def __str__(self):
        return '{} of {} in {}'.format(self.quantity, self.ingredient.name, self.recipe.name)
    
class RecipeImage(models.Model):
    image = models.ImageField(upload_to='images/', null=False)
    description = models.TextField(max_length=255)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='images')

    def __str__(self):
        return '{} Image'.format(self.recipe.name)

recipebook/ledger/forms.py
from django import forms
from .models import Recipe, Ingredient, RecipeIngredient, RecipeImage

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['name']

class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = '__all__'

class RecipeIngredientForm(forms.ModelForm):
    class Meta:
        model = RecipeIngredient
        fields = '__all__'

class RecipeImageForm(forms.ModelForm):
    class Meta:
        model = RecipeImage
        fields = ['image', 'description']

recipebook/ledger/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Recipe
from .forms import RecipeForm, IngredientForm, RecipeIngredientForm, RecipeImageForm

@login_required
def recipe_list(request):
    recipes = Recipe.objects.all()
    return render(request, 'recipe_list.html', {'recipes': recipes})

@login_required
def recipe(request, key):
    recipe = Recipe.objects.get(id=key)
    return render(request, 'recipe.html', {'recipe': recipe})

@login_required
def recipe_maker(request):
    recipe_form = RecipeForm()
    ingredient_form = IngredientForm()
    recipe_ingredient_form = RecipeIngredientForm()
    if request.method == 'POST':
        if 'recipe' in request.POST:
            recipe_form = RecipeForm(request.POST)
            if recipe_form.is_valid():
                recipe_form.instance.author = request.user.profile
                recipe_form.save()
                return redirect('ledger:recipe_list')
            
        if 'ingredient' in request.POST:
            ingredient_form = IngredientForm(request.POST)
            if ingredient_form.is_valid():
                ingredient_form.save()
                
        if 'recipe_ingredient' in request.POST:
            recipe_ingredient_form = RecipeIngredientForm(request.POST)
            if recipe_ingredient_form.is_valid():
                recipe_ingredient_form.save()

    ctx = {'recipe_form':recipe_form, 
           'ingredient_form':ingredient_form, 
           'recipe_ingredient_form':recipe_ingredient_form}
    return render(request, 'recipe_maker.html', ctx)

@login_required
def image_uploader(request, key):
    recipe = Recipe.objects.get(id=key)
    image_form = RecipeImageForm()
    if request.method == 'POST':
        image_form = RecipeImageForm(request.POST, request.FILES)
        if image_form.is_valid():
            recipe_image =  image_form.save(commit=False)
            recipe_image.recipe = recipe
            image_form.save()
            return redirect('ledger:recipe', key=recipe.pk)
    
    ctx = {'recipe':recipe, 'image_form':image_form}
    return render(request, 'image_uploads.html', ctx)

recipebook/ledger/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">
    <title>{% block title %} My amazing site {% endblock %}</title>
    {% block styles %}{% endblock %}
    <h1> Recipe Book </h1>
    <form method="POST" action="{% url 'logout' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"> Logout </button>
    </form>
</head>
<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    {% block scripts %}{% endblock %}
</body>
</html>

recipebook/ledger/templates/image_uploads.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Upload an Image {% endblock %}
{% block content %}
    <h2> Upload an image for {{ recipe.name }} </h2>
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ image_form.as_p }}
        <button type="submit"> Upload image </button>
    </form>

    <a href="{% url 'ledger:recipe_list' %}"> <button type="button"> Back to Recipes List </button> </a>
{% endblock %}

recipebook/ledger/templates/recipe.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ recipe.name }} {% endblock %}
{% block content %}
    <h2> {{ recipe.name }} </h2>
    <h4> Author: {{ recipe.author }} <br>
        Created on: {{ recipe.created_on }} <br>
        Last updated: {{ recipe.updated_on }}
    </h4>

    <h3> Ingredients </h3>
    <ul>
        {% for ingredient in recipe.ingredients.all %}
        <li> {{ ingredient.quantity}} {{ ingredient.ingredient.name }} </li>
        {% endfor %}
    </ul>

    <a href="{% url 'ledger:image_uploader' key=recipe.pk %}"> <button type="button"> Upload an image </button> </a> <br>

    {% if recipe.images.all %}
        {% for image in recipe.images.all %}
            <img src="{{ image.image.url }}" alt="{{ image.description }}">
        {% endfor %}
    {% endif %}

    <br> <a href="{% url 'ledger:recipe_list' %}"> <button type="button"> Back to Recipes List </button> </a>
{% endblock %}

recipebook/ledger/templates/recipe_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Recipe List {% endblock %}
{% block content %}
    <h2> Recipe List </h2>
    <a href="{% url 'ledger:recipe_maker' %}"> <button type="button"> Add a Recipe </button> </a>
    <ul>
        {% for recipe in recipes %}
            <li><a href="{% url 'ledger:recipe' recipe.pk %}"> {{ recipe.name }} </a></li>
        {% endfor %}
    </ul>
{% endblock %}

recipebook/ledger/templates/recipe_maker.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Add a Recipe {% endblock %}
{% block content %}
    <h2> Add a Recipe </h2>
    <form method="post">
        {% csrf_token %}
        {{ recipe_form.as_p }}
        <button type="submit" name="recipe"> Submit </button>
    </form>

    <h2> Add an Ingredient </h2>
    <form method="post">
        {% csrf_token %}
        {{ ingredient_form.as_p }}
        <button type="submit" name="ingredient"> Submit </button>
    </form>

    <h2> Add an Ingredient to a Recipe </h2>
    <form method="post">
        {% csrf_token %}
        {{ recipe_ingredient_form.as_p }}
        <button type="submit" name="recipe_ingredient"> Submit </button>
    </form>

    <a href="{% url 'ledger:recipe_list' %}"> <button type="button"> Back to Recipes List </button> </a>
{% endblock %}